# Generated by Django 5.1.4 on 2024-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
