# Generated by Django 5.1.4 on 2024-12-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id'),
        ('robots', '0003_robot_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='robot_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot'),
        ),
    ]
