# Generated by Django 5.1.4 on 2024-12-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_robot_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='robot_serial',
            new_name='robot',
        ),
    ]
